development:
  adapter: postgresql
  encoding: unicode
  database: chatealo_development
  pool: 5
  host: localhost
  username: agustinvignolosotelo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: chatealo_test
  pool: 5
  username: agustinvignolosotelo
  password:

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
